### ISSUE TITLE
Unable to connect in GitHub actions

### ISSUE THREAD

**Issue by enyo** [mongo-dart/mongo_dart#202]
I'm using GitHub actions, where I create a service that starts a mongodb, and then runs my test jobs inside another (dart) container.

I know that the mongodb server starts properly and that my test container can connect to it properly because I installed the mongo shell inside the container and ran this command successfully:

```bash
$ mongo mongoservice:27017 --eval "db.hostInfo()"
```

But if I try to connect to the connection string in my dart app it fails: `mongodb://mongoservice:27017/integration-test`

The reason I'm suspecting there might be an issue with this library (or maybe dart in general and how it resolves hosts?) is that if I don't run my tests inside a dart container, but directly on the vm, by installing dart there, it all runs fine if I connect to `mongodb://localhost:27017/integration-test`

So it seems to have an issue with the `mongoservice` hostname?

Any help would be appreciated.

My GitHub Action yaml:

```yaml
name: Dart CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    # Not using the container, but installing dart, because I'm using mongodb in
    # another Docker container and need to be able to connect to it. In the long
    # run I plan on implementing a docker compose file for this.
    #
    container:
      image: google/dart:latest

    services:
      mongoservice:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v2
      # -------
      - run: echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.0.list
      - run: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
      - run: apt-get update && apt-get install -y mongodb-org-shell
      - run: mongo mongoservice:27017 --eval "db.hostInfo()"
      # -------

      # - uses: cedx/setup-dart@v2
      #   with:
      #     architecture: x64
      #     release-channel: stable
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart test

```
