### ISSUE TITLE
SocketException: Connection refused (OS Error: Connection refused, errno = 111) with docker setup

### ISSUE THREAD

**Issue by AlessandroMaifredi** [mongo-dart/mongo_dart#351]
Hello, I'm attempting to set up a basic system using docker-compose. This system consists of two services: mongodb and a server built with the shelf package for Dart. Both containers are on the same network (please refer to the docker-compose file), and I believe I've correctly configured all the required environment variables. The error I'm encountering is as follows:
```
MongoDB ConnectionException: Could not connect to mongodb:27017
restfuldart-api  | - SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = mongodb, port = 42302
```

This is the docker-compose file:
```
version: 0.0.2

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
        - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/db_user
        - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/db_password
        - MONGO_INITDB_DATABASE=restfuldart
    volumes:
      - monongodb-volume:/data/db
    networks:
      - mongo-net
    secrets:
      - db_user
      - db_password

  api:
    build: .
    container_name: restfuldart-api
    environment:
      - PORT=8080
      - API_QUERIES_LIMIT=100
      - API_QUERIES_PAGE=1
      - MONGO_DART_DRIVER_HOST=mongodb
      - MONGO_DART_DRIVER_PORT=27017
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - mongo-net
    volumes:
        - restfuldart-volume:/app

networks:
  mongo-net:
    driver: bridge

# simple text files containing a string
secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt

volumes:
    monongodb-volume:
    restfuldart-volume:
```
Below are the two files responsible for creating the server and establishing the connection with the database.

server.dart
```
import 'dart:io';

import 'package:mongo_dart/mongo_dart.dart';
import 'package:restful_dart/db_driver/db_driver.dart';
import 'package:restful_dart/player/player_api.dart';
import 'package:restful_dart/root/root_api.dart';
import 'package:shelf/shelf.dart';
import 'package:shelf/shelf_io.dart';

/// The main entry point for the application
void main(List<String> args) async {
  // Use any available host or container IP (usually `0.0.0.0`).
  final ip = InternetAddress.anyIPv4;
  final port = int.parse(Platform.environment['PORT'] ?? '8080');
  final app = RootApi().router;
  final handler = Pipeline().addMiddleware(logRequests()).addHandler(app);

  final server = await serve(handler, ip, port);
  print('Server listening on port ${server.port}');

  await DbDriver.instance.mongoDb.open();

  print("Using DB: ${DbDriver.instance.mongoDb.databaseName}");

}
```
db_driver.dart
```
import 'dart:io' show Platform;

import 'package:mongo_dart/mongo_dart.dart';

/// A singleton class to manage the database connection
class DbDriver {
  /// The database connection
  final Db _mongoDb = Db('mongodb://mongodb:27017/restfuldart');

  /// The host for the database connection
  /// Use the environment variable MONGO_DART_DRIVER_HOST to override
  /// Defaults to 127.0.0.1
  static final String _host =
      Platform.environment['MONGO_DART_DRIVER_HOST'] ?? '127.0.0.1';

  /// The port for the database connection
  /// Use the environment variable MONGO_DART_DRIVER_PORT to override
  /// Defaults to 27017
  static final String _port =
      Platform.environment['MONGO_DART_DRIVER_PORT'] ?? '27017';

  /// The default limit for queries
  /// Use the environment variable API_DEFAULT_QUERIES_LIMIT to override
  /// Defaults to 10
  static final int defaultQueryLimit = int.tryParse(
          Platform.environment['API_DEFAULT_QUERIES_LIMIT'].toString()) ??
      10;

  /// The default page for queries
  /// Use the environment variable API_DEFAULT_QUERIES_PAGE to override
  /// Defaults to 1
  static int defaultQueryPage = int.tryParse(
          Platform.environment['API_DEFAULT_QUERIES_PAGE'].toString()) ??
      1;

  /// The singleton instance of this class
  static DbDriver get instance => DbDriver._();

  /// A helper factory constructor
  Db get mongoDb => _mongoDb;

  /// Private constructor
  DbDriver._();
}
```

After executing `docker compose up`, everything proceeds smoothly until it reaches the line `await DbDriver.instance.mongoDb.open();` in `server.dart`, at which point the application crashes, generating the following log:

```
restfuldart-api  | Unhandled exception:
restfuldart-api  | MongoDB ConnectionException: Could not connect to mongodb:27017
restfuldart-api  | - SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = mongodb, port = 42302
restfuldart-api  | #0      ConnectionManager.open (package:mongo_dart/src/network/connection_manager.dart:153)
restfuldart-api  | <asynchronous suspension>
restfuldart-api  | #1      Db.open (package:mongo_dart/src/database/db.dart:482)
restfuldart-api  | <asynchronous suspension>
restfuldart-api  | #2      main (file:///app/bin/server.dart:21)
restfuldart-api  | <asynchronous suspension>
```

Note that although the application is attempting to connect on port 27017, the error log consistently displays a random port (which changes with each attempt, in this case 42302)
