### ISSUE TITLE
Unable to connect when MongoDB authentication is turned on

### ISSUE THREAD

**Issue by dukefirehawk** [mongo-dart/mongo_dart#380]
The driver is not working when authentication is turned on for MongoDB even though everything works fine with `mongo-express`.

1. Unable to open connection with `mongodb://root:Qwerty@localhost:27017/local`. Always get Authentication Fail error message.

2. Can run `insertOne` without errors with `mongodb://localhost:27017/local`, but nothing gets inserted into MongoDB. 
 
The above two issues went away when authentication in MongoDB is turned off. 

The following docker compose file and program are used for testing.

```
services:

  mongo:
    image: mongo
    restart: no
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Qwerty
      MONGO_INITDB_DATABASE: testingDB
```

```
void main() async {
    var db = Db('mongodb://localhost:27017/testingDB');
    //var db = Db('mongodb://root:Qwerty@localhost:27017/testingDB');
    await db.open();

    Map<String, dynamic> data = {'name': 'John', 'foo': 'Jim', 'to': 'King'};
    var testData = db.collection('testData');
    var result = await testData.insertOne(data);
    print("write concern error: ${result.hasWriteConcernError}");
    print("write error: ${result.hasWriteErrors}");
    print(result.document);
}
```
